import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { GetStaticProps } from 'next';

import React from 'react';
import { extractLocale } from 'lib/translation-helpers';
import { useTranslation } from 'next-i18next';
import Image from 'next/image';

export default function Home() {
  const { t } = useTranslation('common');

  return (
    <>
      <Head>
        <title>Ada Lowkis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="https://adalowkis-artwork.s3.eu-central-1.amazonaws.com/large_IMG_4029_f19aaf5a5b.jpeg"
        alt="welcome"
      />
    </>
  );
}

export const getStaticProps: GetStaticProps = async (ctx) => ({
  props: {
    ...(await serverSideTranslations(extractLocale(ctx), ['common'])),
  },
});
